### ISSUE TITLE
Don't pass for itunes because of the image property

### ISSUE THREAD

**Issue by technolytic** [lukaswhite/php-feed-writer#1]
Dear @lukaswhite 

I noticed that the feed generated in itunes format don't work anymore with iTunes services (and Spotify which seems to be based on the same structure as for iTunes, see [Podcast Delivery Specification document](https://podcasters.spotify.com/terms/Spotify_Podcast_Delivery_Specification_v1.5.pdf).
The reason is the image property would need to be displayed as:

`<rss>
<channel>
<item>
<itunes:image href="https://example.com/sbig/screenshots/s02e09.png" />
</item>
...
</channel>
</rss>`

with href attribute and not simply:

`<rss>
<channel>
<item>
<itunes:image>https://example.com/sbig/screenshots/s02e09.png</itunes:image>
</item>
...
</channel>
</rss>`

Can you confirm it?

To pass the validation, I wrote a new Trait class HasCoverArt in src/Traits/Itunes similar to HasImage class with addCoverArtElement function returning $this->createElement( 'itunes:image', '', array("href" => $this->coverArt );

I need further tests but it seems to be good so far.

However, thanks for sharing this nice library !
Ugo

**Comment by lukaswhite** [comment]
Hi Ugo,

Thanks for raising this issue, and well spotted.

I'm not sure whether iTunes has changed, but it certainly looks like images for that need to use the `href` attribute ([docs](https://help.apple.com/itc/podcasts_connect/#/itcb54353390)). So, what I've done is made that change and released a new version; `0.2.0`. I've updated the tests for it accordingly.

I hadn't really thought about Spotify, so what I'm going to do is create a new Spotify feed type that extends iTunes, adding:

- The Spotify-specific tags; `spotify:limit` and `spotify:countryoforigin`
- The Dublin Core terms
- Podlove simple chapters support
